apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: x
  janus-idp.io/tekton: x
  backstage.io/kubernetes-id: x
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: x
resources:
- deployment.yaml
- route.yaml
- service.yaml
